export class AuthError extends Error {
  constructor(public code: string, message: string) {
    super(message);
    this.name = "AuthError";
  }
}

export const AuthErrorCodes = {
  PROFILE_NOT_FOUND: "AUTH_PROFILE_NOT_FOUND",
  PROFILE_DISABLED: "AUTH_PROFILE_DISABLED",
  HOST_MISMATCH: "AUTH_PROFILE_HOST_MISMATCH",
  SECRET_NOT_FOUND: "AUTH_SECRET_NOT_FOUND",
  LOGIN_PAGE_FAILED: "AUTH_LOGIN_PAGE_FAILED",
  USERNAME_FIELD_NOT_FOUND: "AUTH_USERNAME_FIELD_NOT_FOUND",
  PASSWORD_FIELD_NOT_FOUND: "AUTH_PASSWORD_FIELD_NOT_FOUND",
  SUBMIT_NOT_FOUND: "AUTH_SUBMIT_NOT_FOUND",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  VERIFICATION_FAILED: "AUTH_VERIFICATION_FAILED",
  SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  SESSION_INVALID: "AUTH_SESSION_INVALID",
  ENCRYPTION_KEY_MISSING: "AUTH_ENCRYPTION_KEY_MISSING",
  MFA_REQUIRED: "AUTH_MFA_REQUIRED",
  PROFILE_BUSY: "AUTH_PROFILE_BUSY",
  ORIGIN_CHANGED: "AUTH_ORIGIN_CHANGED",
  CAPTCHA_REQUIRED: "AUTH_CAPTCHA_REQUIRED",
  EXTERNAL_PROVIDER_REQUIRED: "AUTH_EXTERNAL_PROVIDER_REQUIRED"
};
